// Generated by gencpp from file ur5_pkg/InverseKinematic.msg
// DO NOT EDIT!


#ifndef UR5_PKG_MESSAGE_INVERSEKINEMATIC_H
#define UR5_PKG_MESSAGE_INVERSEKINEMATIC_H

#include <ros/service_traits.h>


#include <ur5_pkg/InverseKinematicRequest.h>
#include <ur5_pkg/InverseKinematicResponse.h>


namespace ur5_pkg
{

struct InverseKinematic
{

typedef InverseKinematicRequest Request;
typedef InverseKinematicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InverseKinematic
} // namespace ur5_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur5_pkg::InverseKinematic > {
  static const char* value()
  {
    return "c7202f6e227428a04da015ed4eae1b79";
  }

  static const char* value(const ::ur5_pkg::InverseKinematic&) { return value(); }
};

template<>
struct DataType< ::ur5_pkg::InverseKinematic > {
  static const char* value()
  {
    return "ur5_pkg/InverseKinematic";
  }

  static const char* value(const ::ur5_pkg::InverseKinematic&) { return value(); }
};


// service_traits::MD5Sum< ::ur5_pkg::InverseKinematicRequest> should match
// service_traits::MD5Sum< ::ur5_pkg::InverseKinematic >
template<>
struct MD5Sum< ::ur5_pkg::InverseKinematicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_pkg::InverseKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::InverseKinematicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_pkg::InverseKinematicRequest> should match
// service_traits::DataType< ::ur5_pkg::InverseKinematic >
template<>
struct DataType< ::ur5_pkg::InverseKinematicRequest>
{
  static const char* value()
  {
    return DataType< ::ur5_pkg::InverseKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::InverseKinematicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur5_pkg::InverseKinematicResponse> should match
// service_traits::MD5Sum< ::ur5_pkg::InverseKinematic >
template<>
struct MD5Sum< ::ur5_pkg::InverseKinematicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_pkg::InverseKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::InverseKinematicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_pkg::InverseKinematicResponse> should match
// service_traits::DataType< ::ur5_pkg::InverseKinematic >
template<>
struct DataType< ::ur5_pkg::InverseKinematicResponse>
{
  static const char* value()
  {
    return DataType< ::ur5_pkg::InverseKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::InverseKinematicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR5_PKG_MESSAGE_INVERSEKINEMATIC_H
