// Generated by gencpp from file ur5_pkg/InverseKinematicRequest.msg
// DO NOT EDIT!


#ifndef UR5_PKG_MESSAGE_INVERSEKINEMATICREQUEST_H
#define UR5_PKG_MESSAGE_INVERSEKINEMATICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_pkg
{
template <class ContainerAllocator>
struct InverseKinematicRequest_
{
  typedef InverseKinematicRequest_<ContainerAllocator> Type;

  InverseKinematicRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  InverseKinematicRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InverseKinematicRequest_

typedef ::ur5_pkg::InverseKinematicRequest_<std::allocator<void> > InverseKinematicRequest;

typedef boost::shared_ptr< ::ur5_pkg::InverseKinematicRequest > InverseKinematicRequestPtr;
typedef boost::shared_ptr< ::ur5_pkg::InverseKinematicRequest const> InverseKinematicRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator1> & lhs, const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator1> & lhs, const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_pkg/InverseKinematicRequest";
  }

  static const char* value(const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InverseKinematicRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_pkg::InverseKinematicRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_PKG_MESSAGE_INVERSEKINEMATICREQUEST_H
