// Generated by gencpp from file ur5_pkg/JacobianKinematicResponse.msg
// DO NOT EDIT!


#ifndef UR5_PKG_MESSAGE_JACOBIANKINEMATICRESPONSE_H
#define UR5_PKG_MESSAGE_JACOBIANKINEMATICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_pkg
{
template <class ContainerAllocator>
struct JacobianKinematicResponse_
{
  typedef JacobianKinematicResponse_<ContainerAllocator> Type;

  JacobianKinematicResponse_()
    : output(0.0)  {
    }
  JacobianKinematicResponse_(const ContainerAllocator& _alloc)
    : output(0.0)  {
  (void)_alloc;
    }



   typedef double _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JacobianKinematicResponse_

typedef ::ur5_pkg::JacobianKinematicResponse_<std::allocator<void> > JacobianKinematicResponse;

typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicResponse > JacobianKinematicResponsePtr;
typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicResponse const> JacobianKinematicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator1> & lhs, const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator1> & lhs, const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dd87a43ba76105996c6c8cafb738498";
  }

  static const char* value(const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dd87a43ba761059ULL;
  static const uint64_t static_value2 = 0x96c6c8cafb738498ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_pkg/JacobianKinematicResponse";
  }

  static const char* value(const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 output\n"
;
  }

  static const char* value(const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacobianKinematicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_pkg::JacobianKinematicResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<double>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_PKG_MESSAGE_JACOBIANKINEMATICRESPONSE_H
