// Generated by gencpp from file ur5_pkg/JacobianKinematic.msg
// DO NOT EDIT!


#ifndef UR5_PKG_MESSAGE_JACOBIANKINEMATIC_H
#define UR5_PKG_MESSAGE_JACOBIANKINEMATIC_H

#include <ros/service_traits.h>


#include <ur5_pkg/JacobianKinematicRequest.h>
#include <ur5_pkg/JacobianKinematicResponse.h>


namespace ur5_pkg
{

struct JacobianKinematic
{

typedef JacobianKinematicRequest Request;
typedef JacobianKinematicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JacobianKinematic
} // namespace ur5_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur5_pkg::JacobianKinematic > {
  static const char* value()
  {
    return "6c59364dede48a4429627e3e0efa7049";
  }

  static const char* value(const ::ur5_pkg::JacobianKinematic&) { return value(); }
};

template<>
struct DataType< ::ur5_pkg::JacobianKinematic > {
  static const char* value()
  {
    return "ur5_pkg/JacobianKinematic";
  }

  static const char* value(const ::ur5_pkg::JacobianKinematic&) { return value(); }
};


// service_traits::MD5Sum< ::ur5_pkg::JacobianKinematicRequest> should match
// service_traits::MD5Sum< ::ur5_pkg::JacobianKinematic >
template<>
struct MD5Sum< ::ur5_pkg::JacobianKinematicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_pkg::JacobianKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::JacobianKinematicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_pkg::JacobianKinematicRequest> should match
// service_traits::DataType< ::ur5_pkg::JacobianKinematic >
template<>
struct DataType< ::ur5_pkg::JacobianKinematicRequest>
{
  static const char* value()
  {
    return DataType< ::ur5_pkg::JacobianKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::JacobianKinematicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur5_pkg::JacobianKinematicResponse> should match
// service_traits::MD5Sum< ::ur5_pkg::JacobianKinematic >
template<>
struct MD5Sum< ::ur5_pkg::JacobianKinematicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_pkg::JacobianKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::JacobianKinematicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_pkg::JacobianKinematicResponse> should match
// service_traits::DataType< ::ur5_pkg::JacobianKinematic >
template<>
struct DataType< ::ur5_pkg::JacobianKinematicResponse>
{
  static const char* value()
  {
    return DataType< ::ur5_pkg::JacobianKinematic >::value();
  }
  static const char* value(const ::ur5_pkg::JacobianKinematicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR5_PKG_MESSAGE_JACOBIANKINEMATIC_H
