// Generated by gencpp from file ur5_pkg/JacobianKinematicRequest.msg
// DO NOT EDIT!


#ifndef UR5_PKG_MESSAGE_JACOBIANKINEMATICREQUEST_H
#define UR5_PKG_MESSAGE_JACOBIANKINEMATICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_pkg
{
template <class ContainerAllocator>
struct JacobianKinematicRequest_
{
  typedef JacobianKinematicRequest_<ContainerAllocator> Type;

  JacobianKinematicRequest_()
    : input(0.0)  {
    }
  JacobianKinematicRequest_(const ContainerAllocator& _alloc)
    : input(0.0)  {
  (void)_alloc;
    }



   typedef double _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JacobianKinematicRequest_

typedef ::ur5_pkg::JacobianKinematicRequest_<std::allocator<void> > JacobianKinematicRequest;

typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicRequest > JacobianKinematicRequestPtr;
typedef boost::shared_ptr< ::ur5_pkg::JacobianKinematicRequest const> JacobianKinematicRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator1> & lhs, const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator1> & lhs, const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "235c8ad2b88a9725a5a2ad2a9541a007";
  }

  static const char* value(const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x235c8ad2b88a9725ULL;
  static const uint64_t static_value2 = 0xa5a2ad2a9541a007ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_pkg/JacobianKinematicRequest";
  }

  static const char* value(const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 input\n"
;
  }

  static const char* value(const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacobianKinematicRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_pkg::JacobianKinematicRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<double>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_PKG_MESSAGE_JACOBIANKINEMATICREQUEST_H
